### ISSUE TITLE
Create `test/fixtures/walkman/` if it doesn't exist

### ISSUE THREAD

**Issue by jonleighton** [derekkraan/walkman#14]
If this path isn't present, Walkman will exit with an error:

```
  ▏ ▏** (exit) exited in: GenServer.call(#PID<0.777.0>, :finish, 5000)
  ▏ ▏ ▏ ▏** (EXIT) an exception was raised:
  ▏ ▏ ▏ ▏ ▏ ▏** (File.Error) could not write to file "test/fixtures/walkman/my_tape_name": no such file or directory
  ▏ ▏ ▏ ▏ ▏ ▏ ▏ ▏(elixir 1.11.2) lib/file.ex:1052: File.write!/3
  ▏ ▏ ▏ ▏ ▏ ▏ ▏ ▏(walkman 0.3.3) lib/walkman/tape.ex:172: Walkman.Tape.handle_call/3
  ▏ ▏ ▏ ▏ ▏ ▏ ▏ ▏(stdlib 3.13.2) gen_server.erl:706: :gen_server.try_handle_call/4
  ▏ ▏ ▏ ▏ ▏ ▏ ▏ ▏(stdlib 3.13.2) gen_server.erl:735: :gen_server.handle_msg/6
  ▏ ▏ ▏ ▏ ▏ ▏ ▏ ▏(stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

It also looks like the directory is hard-coded -- it would be nice to make it configurable.

**Comment by derekkraan** [comment]
Hi Jon,

I would accept a PR for both issues.
